<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
        <IsPackable>true</IsPackable>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <Description>This NuGet contains helpers to better integrate Ev.ServiceBus with Mvc projects.</Description>
        <PackageProjectUrl>https://github.com/EcovadisCode/Ev.ServiceBus</PackageProjectUrl>
        <RepositoryUrl>https://github.com/EcovadisCode/Ev.ServiceBus</RepositoryUrl>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Ev.ServiceBus.Abstractions\Ev.ServiceBus.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
      <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

</Project>
