name: publish NuGet packages by tag
on:
  create:
    tags:
      - '*'
jobs:
  publish:
    name: build, pack & publish
    runs-on: windows-latest
    steps:
      - name: retrieve version number
        uses: actions-ecosystem/action-regex-match@v2
        id: get-version
        with:
          text: ${{ github.ref }}
          regex: '/[0-9]+.[0-9]+.[0-9]+-?[0-9a-z]*/'
      - name: Check version or Exit
        id: check-version
        shell: bash
        if: steps.get-version.match == ''
        run: |
          echo Version number extracted from ${GITHUB_REF} is invalid
          exit 1
#      - name: Get the version from ${{ github.ref }}
#        id: get_version
#        shell: bash
#        run: |
#          echo Publishing version ${GITHUB_REF#refs/tags/} of packages
#          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - uses: actions/checkout@v2
      - name: Setup .NET 2.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.813
      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.406
      - name: Setup .NET Core 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.102
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore -p:Version=${{steps.get_version.outputs.VERSION}}
      - name: Pack
        run: dotnet pack --configuration Release --no-build --no-restore -v normal -o ./nupkgs -p:Version=${{steps.get_version.outputs.VERSION}}
#      - name: Push
#        run: dotnet nuget push ./nupkgs -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org --skip-duplicate -n 
